# Generated by Django 4.2.16 on 2024-11-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchQueries",
            fields=[
                ("query_id", models.AutoField(primary_key=True, serialize=False)),
                ("keyword", models.CharField(max_length=200)),
                ("date_queried", models.DateField()),
                ("date_range_button", models.CharField(max_length=30)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "db_table": "SearchQueries",
                "managed": False,
            },
        ),
    ]
