# Generated by Django 4.2.16 on 2024-11-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databaseApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_broadcast", models.DateField()),
                ("headline", models.CharField(max_length=500)),
                ("subline", models.CharField(max_length=1000)),
                ("url", models.CharField(max_length=1000)),
                ("parsed_domain", models.CharField(max_length=255)),
                ("image", models.CharField(blank=True, max_length=1000, null=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("article_type", models.CharField(max_length=100)),
                ("publication_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Article",
                "managed": False,
            },
        ),
    ]
