# Generated by Django 4.2.16 on 2024-10-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customuser",
            table="USER",
        ),
    ]
