# Generated by Django 4.2.16 on 2024-11-05 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_alter_customuser_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="PasswordHash",
        ),
    ]
